feat!: #35 ensure document metadata is set (#45) (#47)
* feat!: #35 ensure document metadata is set
* build: add error check when writing build metadata
* ci: don't print date & version in render
---------

Co-authored-by: Richard Henning <1392051+rhenning@users.noreply.github.com>

diff --git a/.github/workflows/convert_and_release.yaml b/.github/workflows/convert_and_release.yaml
--- a/.github/workflows/convert_and_release.yaml
+++ b/.github/workflows/convert_and_release.yaml
@@ -14,9 +14,7 @@ env:
   srcdir: src
   srcdoc: professional.md
   builddir: build
-  papersize: letter
   prefix: richard_henning-professional_resume
-  title: Professional Résumé – Richard Henning
 
 jobs:
   convert:
@@ -37,10 +35,21 @@ jobs:
       - name: Get additional git repository metadata
         id: get_repometa
         run: |
-          echo "short_sha=$( git rev-parse --short ${{ github.sha }} )" >> $GITHUB_OUTPUT
+          ## fail on common errors
+          set -o errexit -o nounset -o pipefail
+          ## enable debug tracing - uncomment for debugging
+          # set -o xtrace
+          ## write metadata to GHA environment variables
+          echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
+          echo "date=$(date --iso-8601=seconds --utc | tr -d ':-' )" >> $GITHUB_OUTPUT
 
       - name: Generate build metadata
         run: |
+          ## fail on common errors
+          set -o errexit -o nounset -o pipefail
+          ## enable debug tracing - uncomment for debugging
+          # set -o xtrace
+          ## write metadata to a JSON file for inclusion in the release
           cat <<-__END__ > "${{ env.builddir }}/BUILDMETA.json"
           {
             "github": {
@@ -48,7 +57,8 @@ jobs:
               "repository": "${{ github.repository }}",
               "ref": "${{ github.ref }}",
               "sha": "${{ github.sha }}",
-              "short_sha": "${{ steps.get_repometa.outputs.short_sha }}"
+              "short_sha": "${{ steps.get_repometa.outputs.short_sha }}",
+              "date": "${{ steps.get_repometa.outputs.date }}"
             }
           }
           __END__
@@ -60,7 +70,8 @@ jobs:
             --standalone
             --from gfm
             --to gfm
-            --metadata version="${{ steps.get_repometa.outputs.short_sha }}"
+            --metadata version-meta="${{ steps.get_repometa.outputs.short_sha }}"
+            --metadata date-meta="${{ steps.get_repometa.outputs.date }}"
             --output="./${{ env.builddir }}/${{ env.prefix }}.md"
             "./${{ env.srcdir }}/${{ env.srcdoc }}"
 
@@ -71,9 +82,8 @@ jobs:
             --standalone
             --template eisvogel
             --from gfm
-            --variable papersize="${{ env.papersize }}"
-            --metadata title="${{ env.title }}"
-            --metadata version="${{ steps.get_repometa.outputs.short_sha }}"
+            --metadata version-meta="${{ steps.get_repometa.outputs.short_sha }}"
+            --metadata date-meta="${{ steps.get_repometa.outputs.date }}"
             --output="./${{ env.builddir }}/${{ env.prefix }}.pdf"
             "./${{ env.srcdir }}/${{ env.srcdoc }}"
 
@@ -83,8 +93,8 @@ jobs:
           args: >-
             --standalone
             --from gfm
-            --metadata title="${{ env.title }}"
-            --metadata version="${{ steps.get_repometa.outputs.short_sha }}"
+            --metadata version-meta="${{ steps.get_repometa.outputs.short_sha }}"
+            --metadata date-meta="${{ steps.get_repometa.outputs.date }}"
             --output="./${{ env.builddir }}/${{ env.prefix }}.docx"
             "./${{ env.srcdir }}/${{ env.srcdoc }}"
 
@@ -94,8 +104,8 @@ jobs:
           args: >-
             --standalone
             --from gfm
-            --metadata title="${{ env.title }}"
-            --metadata version="${{ steps.get_repometa.outputs.short_sha }}"
+            --metadata version-meta="${{ steps.get_repometa.outputs.short_sha }}"
+            --metadata date-meta="${{ steps.get_repometa.outputs.date }}"
             --output="./${{ env.builddir }}/${{ env.prefix }}.html"
             "./${{ env.srcdir }}/${{ env.srcdoc }}"
 
